# Generated by Django 4.2.30 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
