# Generated by Django 4.2.30 on 2026-08-06 10:36

from django.db import migrations, models


def deduplicate_names(apps, schema_editor):
    """Make customer names unique before the constraint is applied.

    Nothing stopped duplicates before, and adding the unique index would fail
    on any that exist. Suffix the later ones rather than merging, so no data
    is lost and a human can reconcile them afterwards.
    """
    Customer = apps.get_model("invoices", "Customer")

    seen = set()

    for customer in Customer.objects.order_by("id").iterator():
        name = customer.name

        if name not in seen:
            seen.add(name)
            continue

        suffix = 2
        while f"{name} ({suffix})" in seen:
            suffix += 1

        customer.name = f"{name} ({suffix})"[:255]
        customer.save(update_fields=["name"])
        seen.add(customer.name)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_backfill_user_roles"),
    ]

    operations = [
        migrations.RunPython(deduplicate_names, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="license_no",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pharmacy licence"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="ntn",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CNIC / NTN"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sales_tax",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Sales tax registration",
            ),
        ),
    ]
