# Generated by Django 4.2.30 on 2026-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_seed_default_distributor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="territory",
            options={
                "ordering": ["city", "code", "name"],
                "verbose_name_plural": "territories",
            },
        ),
        migrations.AddField(
            model_name="callpoint",
            name="estimated_volume",
            field=models.CharField(
                blank=True,
                help_text="Rough size, e.g. '250+' doctors or '150+ Chemists'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Short reference used on tour plans, e.g. N-01.",
                max_length=20,
            ),
        ),
    ]
