# Generated by Django 4.2.30 on 2026-08-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0011_alter_territory_options_callpoint_estimated_volume_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                (
                    "country",
                    models.CharField(blank=True, default="Pakistan", max_length=80),
                ),
                (
                    "drug_licence",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Drug manufacturing licence",
                    ),
                ),
                ("ntn", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="generic_name",
            field=models.CharField(
                blank=True,
                help_text="Active ingredient, e.g. Paracetamol 500mg.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="registration_no",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="DRAP registration"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="invoices.manufacturer",
            ),
        ),
    ]
