# Generated by Django 4.2.30 on 2026-08-07 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0015_seed_expense_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("visit_time", models.TimeField(blank=True, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                ("speciality", models.CharField(blank=True, max_length=120)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("met", "Doctor met"),
                            ("not_available", "Not available"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="met",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_reports",
                        to="invoices.callpoint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_reports",
                        to="invoices.employee",
                    ),
                ),
                (
                    "plan_visit",
                    models.OneToOneField(
                        blank=True,
                        help_text="The scheduled slot this fulfils, when it was planned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report",
                        to="invoices.planvisit",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="What was detailed on this call.",
                        related_name="call_reports",
                        to="invoices.product",
                    ),
                ),
                (
                    "sample_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_reports",
                        to="invoices.sampleissue",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-visit_time", "-id"],
            },
        ),
    ]
