# Generated by Django 4.2.30 on 2026-08-08 09:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0016_callreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage of net sales, on top of salary. Leave at 0 for staff on salary only.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member credited with this sale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.employee",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="commission",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="sales_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Net sales credited to this employee for the month.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="userrolls",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("manager", "Manager"),
                    ("field", "Field Staff (MR)"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
    ]
