# Generated by Django 5.2.17 on 2026-08-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0019_doctors_from_call_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="callreport",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier generated on the device, for offline sync.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="callreport",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="invoices.doctor",
            ),
        ),
        migrations.AddField(
            model_name="callreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
