# Generated by Django 4.2.30 on 2026-08-09 13:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0020_callreport_client_uuid_callreport_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=20, unique=True)),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Who the goods are for, as the MR wrote it.",
                        max_length=255,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True)),
                ("contact_number", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
                (
                    "required_by",
                    models.DateField(
                        blank=True, help_text="When the customer wants it.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting the office"),
                            ("approved", "Approved, not yet invoiced"),
                            ("invoiced", "Invoiced"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled by the MR"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client_uuid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "call_point",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where to deliver, when the order came from a call.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="invoices.callpoint",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Left blank when the pharmacy is not on the books yet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="invoices.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The MR who took the order.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="invoices.employee",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="invoices.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
