# Generated by Django 4.2.30 on 2026-08-14 09:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0027_supplier_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("cash", "Cash in hand"), ("bank", "Bank account")],
                        default="bank",
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=60)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="What was in it the day you started using this system.",
                        max_digits=14,
                    ),
                ),
                (
                    "opened_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Pre-selected when money is recorded."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="capitaltransaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_entries",
                to="invoices.account",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="invoices.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_payments",
                to="invoices.account",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_payments",
                to="invoices.account",
            ),
        ),
    ]
