# Generated by Django 4.2.30 on 2026-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0028_cash_and_bank_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="bonus",
            field=models.IntegerField(
                default=0, help_text="Free packs given with this line, not charged for."
            ),
        ),
    ]
