# Generated by Django 4.2.30 on 2026-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0029_item_bonus_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreturnitem",
            name="bonus",
            field=models.IntegerField(default=0),
        ),
    ]
